version: "3"

services:
  database-name:
    container_name: database-name
    image: postgres # or mysql or mariadb etc
    ports:
      - 5432:5432 # first is host port, second is container port
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=entcar
      - POSTGRES_DB=databaseName
